version: '3.7'
services:
  igrill:
    image: igrill
    build:
      context: .
      dockerfile: Dockerfile.armv6
    container_name: igrill
    privileged: true
    network_mode: host
    restart: always
    logging:
      # This is running on a low-power device, and the "local" driver is an
      # optimized binary format. Default is JSON.
      driver: "local"
      options:
        max-size: "5m"
        max-files: 3
